"""Safety validator for visualisation HTML generated by Gemini.

Checks that the HTML is safe to render in a sandboxed iframe with
only `allow-scripts` — no external resources, no network calls, no eval.
"""

MAX_HTML_LENGTH = 50_000


def validate_visual_html(html: str) -> tuple[bool, str]:
    """Validate that HTML is safe for sandboxed iframe rendering.

    Returns:
        (is_valid: bool, reason: str) — reason is empty if valid.
    """
    if not html or not isinstance(html, str):
        return False, "HTML content is empty or not a string"

    if len(html) > MAX_HTML_LENGTH:
        return False, f"HTML exceeds size limit of {MAX_HTML_LENGTH} characters"

    if "<script src" in html:
        return False, "External script tags are not allowed"

    if "fetch(" in html or "XMLHttpRequest" in html or "XMLHttpRequest" in html:
        return False, "Network calls (fetch/XMLHttpRequest) are not allowed"

    if "eval(" in html or "new Function(" in html:
        return False, "eval() and new Function() are not allowed"

    if "document.write(" in html:
        return False, "document.write() is not allowed"

    if "import(" in html:
        return False, "dynamic import() is not allowed"

    if not all(tag in html for tag in ["<html", "<body", "<script"]):
        return False, "HTML is not a complete document (missing <html>, <body>, or <script>)"

    return True, ""
